# Generated by Django 5.2 on 2025-06-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='perfiles/perfil_defecto.jpg', null=True, upload_to='perfiles/'),
        ),
    ]
